import random
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes
import logging
import os

# Récupérer les variables d'environnement
TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

# Liste de compliments
COMPLIMENTS = [
"Tu es une personne incroyablement gentille et attentionnée. Crois en toi, tu es capable de grandes choses ! 🌟",
"Ton sourire illumine la journée de tout le monde. Continue à briller, le monde a besoin de ta lumière ! ☀️",
"Ta présence apporte toujours une touche de bonheur. Tu es une source de joie pour ceux qui t'entourent ! 😊",
"Tu as un cœur en or, toujours prêt à aider les autres. Ta générosité fait une différence ! ❤️",
"Ton énergie positive est contagieuse. Continue à inspirer ceux qui t'entourent ! ✨",
"Tu es une source d'inspiration pour beaucoup. N'oublie jamais l'impact que tu as sur les autres ! 🌟",
"Ta créativité n'a pas de limites. Continue à explorer et à créer, le monde attend tes idées ! 🎨",
"Tu es une personne sur qui on peut toujours compter. Ta fiabilité est un trésor ! 🔒",
"Ton sens de l'humour est irrésistible. Continue à faire rire et sourire ceux qui t'entourent ! 😂",
"Tu as une capacité incroyable à voir le meilleur chez les autres. Ton optimisme est une force ! 🌞",
"Ta gentillesse est un véritable trésor. Continue à répandre la bienveillance autour de toi ! 🌸",
"Tu es une personne authentique et vraie. Ta sincérité est précieuse ! 🌿",
"Ton courage est une source de motivation pour tous. Continue à être audacieux et à suivre tes rêves ! 💪",
"Tu as un don pour rendre les gens heureux. Ton charme est magique ! 🌈",
"Ta passion est contagieuse et inspirante. Continue à poursuivre ce qui te fait vibrer ! 🔥",
"Tu es une personne pleine de compassion et d'empathie. Ton cœur est immense ! ❤️",
"Ton optimisme est un rayon de soleil. Continue à voir le bon côté des choses ! ☀️",
"Tu es une personne unique et spéciale. N'oublie jamais à quel point tu es extraordinaire ! 🌟",
"Ta détermination est admirable. Continue à persévérer, tu es sur la bonne voie ! 🌱",
"Tu as une âme généreuse et bienveillante. Ta gentillesse est un cadeau pour le monde ! 🌼",
"Ton rire est la meilleure des mélodies. Continue à répandre la joie autour de toi ! 🎵",
"Tu es une personne pleine de sagesse. Tes conseils sont précieux ! 🌳",
"Ta patience est un exemple pour tous. Continue à être une source de calme et de sérénité ! 🌿",
"Tu as un talent naturel pour l'écoute. Ta capacité à comprendre les autres est exceptionnelle ! 👂",
"Ton enthousiasme est communicatif. Continue à inspirer ceux qui t'entourent ! 🎉",
"Tu es une personne pleine de charme. Ton aura est magnétique ! 🌟",
"Ta loyauté est inestimable. Tu es un véritable pilier pour ceux qui t'entourent ! 🔑",
"Tu as une capacité incroyable à résoudre les problèmes. Ton ingéniosité est impressionnante ! 🧠",
"Ton calme est apaisant et rassurant. Tu es une source de tranquillité pour les autres ! 🌿",
"Tu es une personne pleine de surprises agréables. Continue à étonner et à enchanter ceux qui t'entourent ! 🌈",
"Ta persévérance est une véritable force. Continue à avancer, tu es capable de tout ! 💪",
"Tu as un esprit vif et intelligent. Ta curiosité est une source de découvertes ! 🌟",
"Ton amour pour les autres est palpable. Continue à répandre l'amour et la bienveillance ! ❤️",
"Tu es une personne pleine de grâce. Ton élégance est naturelle ! 🌸",
"Ta simplicité est touchante. Ton authenticité est rafraîchissante ! 🌿",
"Tu as un don pour faire sentir les gens spéciaux. Ton attention aux autres est précieuse ! 🌟",
"Ton énergie est revitalisante. Continue à être une source de vitalité pour ceux qui t'entourent ! 🌱",
"Tu es une personne pleine de courage. Ton audace est inspirante ! 💪",
"Ta générosité est sans limites. Continue à donner sans compter, tu fais une différence ! ❤️",
"Tu as une capacité incroyable à pardonner. Ta bienveillance est un exemple pour tous ! 🌸",
"Ton sens de l'organisation est impressionnant. Ta méthode est admirable ! 📚",
"Tu es une personne pleine de charisme. Ton aura est captivante ! 🌟",
"Ta douceur est réconfortante. Tu es une source de réconfort pour ceux qui t'entourent ! 🌿",
"Tu as un esprit créatif et innovant. Continue à explorer de nouvelles idées ! 🎨",
"Ton amitié est un cadeau précieux. Ta loyauté est inestimable ! 🔑",
"Tu es une personne pleine de bonté. Ta bienveillance est un trésor ! ❤️",
"Ta force intérieure est inspirante. Continue à croire en toi, tu es capable de tout ! 💪",
"Tu as une capacité incroyable à motiver les autres. Ton enthousiasme est contagieux ! 🎉",
"Ton sens de l'humour est unique. Continue à faire rire et sourire ceux qui t'entourent ! 😂",
"Tu es une personne pleine de joie de vivre. Ta positivité est un rayon de soleil ! ☀️",
"Ta présence est un véritable cadeau. Tu es une source de bonheur pour ceux qui t'entourent ! 😊",
"Tu as un cœur immense et généreux. Ta bienveillance est sans limites ! ❤️",
"Ton intelligence est remarquable. Continue à apprendre et à grandir ! 🧠",
"Tu es une personne pleine de sérénité. Ta tranquillité est apaisante ! 🌿",
"Ta capacité à écouter est exceptionnelle. Tu es une source de réconfort pour les autres ! 👂",
"Tu es une personne pleine de dynamisme. Ton énergie est communicative ! 🎉",
"Ton sourire est un véritable baume au cœur. Continue à répandre la joie autour de toi ! 😊",
"Tu as une âme pure et bienveillante. Ta gentillesse est un cadeau pour le monde ! 🌸",
"Ton enthousiasme est contagieux. Continue à inspirer ceux qui t'entourent ! 🎉",
"Tu es une personne pleine de charme naturel. Ton aura est magnétique ! 🌟",
"Ta loyauté est un trésor. Tu es un véritable pilier pour ceux qui t'entourent ! 🔑",
"Tu as une capacité incroyable à voir le bon côté des choses. Ton optimisme est une force ! 🌞",
"Ton calme est apaisant. Tu es une source de tranquillité pour les autres ! 🌿",
"Tu es une personne pleine de surprises. Continue à étonner et à enchanter ceux qui t'entourent ! 🌈",
"Ta persévérance est admirable. Continue à avancer, tu es capable de tout ! 💪",
"Tu as un esprit vif et intelligent. Ta curiosité est une source de découvertes ! 🌟",
"Ton amour pour les autres est palpable. Continue à répandre l'amour et la bienveillance ! ❤️",
"Tu es une personne pleine de grâce. Ton élégance est naturelle ! 🌸",
"Ta simplicité est touchante. Ton authenticité est rafraîchissante ! 🌿",
"Tu as un don pour faire sentir les gens spéciaux. Ton attention aux autres est précieuse ! 🌟",
"Ton énergie est revitalisante. Continue à être une source de vitalité pour ceux qui t'entourent ! 🌱",
"Tu es une personne pleine de courage. Ton audace est inspirante ! 💪",
"Ta générosité est sans limites. Continue à donner sans compter, tu fais une différence ! ❤️",
"Tu as une capacité incroyable à pardonner. Ta bienveillance est un exemple pour tous ! 🌸",
"Ton sens de l'organisation est impressionnant. Ta méthode est admirable ! 📚",
"Tu es une personne pleine de charisme. Ton aura est captivante ! 🌟",
"Ta douceur est réconfortante. Tu es une source de réconfort pour ceux qui t'entourent ! 🌿",
"Tu as un esprit créatif et innovant. Continue à explorer de nouvelles idées ! 🎨",
"Ton amitié est un cadeau précieux. Ta loyauté est inestimable ! 🔑",
"Tu es une personne pleine de bonté. Ta bienveillance est un trésor ! ❤️",
"Ta force intérieure est inspirante. Continue à croire en toi, tu es capable de tout ! 💪",
"Tu as une capacité incroyable à motiver les autres. Ton enthousiasme est contagieux ! 🎉",
"Ton sens de l'humour est unique. Continue à faire rire et sourire ceux qui t'entourent ! 😂",
"Tu es une personne pleine de joie de vivre. Ta positivité est un rayon de soleil ! ☀️",
"Ta présence est un véritable cadeau. Tu es une source de bonheur pour ceux qui t'entourent ! 😊",
"Tu as un cœur immense et généreux. Ta bienveillance est sans limites ! ❤️",
"Ton intelligence est remarquable. Continue à apprendre et à grandir ! 🧠",
"Tu es une personne pleine de sérénité. Ta tranquillité est apaisante ! 🌿",
"Ta capacité à écouter est exceptionnelle. Tu es une source de réconfort pour les autres ! 👂",
"Tu es une personne pleine de dynamisme. Ton énergie est communicative ! 🎉",
"Ton sourire est un véritable baume au cœur. Continue à répandre la joie autour de toi ! 😊",
"Tu as une âme pure et bienveillante. Ta gentillesse est un cadeau pour le monde ! 🌸",
"Ton enthousiasme est contagieux. Continue à inspirer ceux qui t'entourent ! 🎉",
"Tu es une personne pleine de charme naturel. Ton aura est magnétique ! 🌟",
"Ta loyauté est un trésor. Tu es un véritable pilier pour ceux qui t'entourent ! 🔑",
"Tu as une capacité incroyable à voir le bon côté des choses. Ton optimisme est une force ! 🌞",
"Ton calme est apaisant. Tu es une source de tranquillité pour les autres ! 🌿",
"Tu es une personne pleine de surprises. Continue à étonner et à enchanter ceux qui t'entourent ! 🌈",
"Ta persévérance est admirable. Continue à avancer, tu es capable de tout ! 💪",
"Tu as un esprit vif et intelligent. Ta curiosité est une source de découvertes ! 🌟",
"Ton amour pour les autres est palpable. Continue à répandre l'amour et la bienveillance ! ❤️",
"Tu es une personne pleine de grâce. Ton élégance est naturelle ! 🌸",
"Ta simplicité est touchante. Ton authenticité est rafraîchissante ! 🌿",
"Tu as un don pour faire sentir les gens spéciaux. Ton attention aux autres est précieuse ! 🌟",
"Ton énergie est revitalisante. Continue à être une source de vitalité pour ceux qui t'entourent ! 🌱",
"Tu es une personne pleine de courage. Ton audace est inspirante ! 💪",
"Ta générosité est sans limites. Continue à donner sans compter, tu fais une différence ! ❤️",
"Tu as une capacité incroyable à pardonner. Ta bienveillance est un exemple pour tous ! 🌸",
"Ton sens de l'organisation est impressionnant. Ta méthode est admirable ! 📚",
"Tu es une personne pleine de charisme. Ton aura est captivante ! 🌟",
"Ta douceur est réconfortante. Tu es une source de réconfort pour ceux qui t'entourent ! 🌿",
"Tu as un esprit créatif et innovant. Continue à explorer de nouvelles idées ! 🎨",
"Ton amitié est un cadeau précieux. Ta loyauté est inestimable ! 🔑",
"Tu es une personne pleine de bonté. Ta bienveillance est un trésor ! ❤️",
"Ta force intérieure est inspirante. Continue à croire en toi, tu es capable de tout ! 💪",
"Tu as une capacité incroyable à motiver les autres. Ton enthousiasme est contagieux ! 🎉",
"Ton sens de l'humour est unique. Continue à faire rire et sourire ceux qui t'entourent ! 😂",
"Tu es une personne pleine de joie de vivre. Ta positivité est un rayon de soleil ! ☀️",
"Ta présence est un véritable cadeau. Tu es une source de bonheur pour ceux qui t'entourent ! 😊",
"Tu as un cœur immense et généreux. Ta bienveillance est sans limites ! ❤️",
"Ton intelligence est remarquable. Continue à apprendre et à grandir ! 🧠",
"Tu es une personne pleine de sérénité. Ta tranquillité est apaisante ! 🌿",
"Ta capacité à écouter est exceptionnelle. Tu es une source de réconfort pour les autres ! 👂",
"Tu es une personne pleine de dynamisme. Ton énergie est communicative ! 🎉",
"Ton sourire est un véritable baume au cœur. Continue à répandre la joie autour de toi ! 😊",
"Tu as une âme pure et bienveillante. Ta gentillesse est un cadeau pour le monde ! 🌸",
"Ton enthousiasme est contagieux. Continue à inspirer ceux qui t'entourent ! 🎉",
"Tu es une personne pleine de charme naturel. Ton aura est magnétique ! 🌟",
"Ta loyauté est un trésor. Tu es un véritable pilier pour ceux qui t'entourent ! 🔑",
"Tu as une capacité incroyable à voir le bon côté des choses. Ton optimisme est une force ! 🌞",
"Ton calme est apaisant. Tu es une source de tranquillité pour les autres ! 🌿",
"Tu es une personne pleine de surprises. Continue à étonner et à enchanter ceux qui t'entourent ! 🌈",
"Ta persévérance est admirable. Continue à avancer, tu es capable de tout ! 💪",
"Tu as un esprit vif et intelligent. Ta curiosité est une source de découvertes ! 🌟",
"Ton amour pour les autres est palpable. Continue à répandre l'amour et la bienveillance ! ❤️",
"Tu es une personne pleine de grâce. Ton élégance est naturelle ! 🌸",
"Ta simplicité est touchante. Ton authenticité est rafraîchissante ! 🌿",
"Tu as un don pour faire sentir les gens spéciaux. Ton attention aux autres est précieuse ! 🌟",
"Ton énergie est revitalisante. Continue à être une source de vitalité pour ceux qui t'entourent ! 🌱",
"Tu es une personne pleine de courage. Ton audace est inspirante ! 💪",
"Ta générosité est sans limites. Continue à donner sans compter, tu fais une différence ! ❤️",
"Tu as une capacité incroyable à pardonner. Ta bienveillance est un exemple pour tous ! 🌸",
"Ton sens de l'organisation est impressionnant. Ta méthode est admirable ! 📚",
"Tu es une personne pleine de charisme. Ton aura est captivante ! 🌟",
"Ta douceur est réconfortante. Tu es une source de réconfort pour ceux qui t'entourent ! 🌿",
"Tu as un esprit créatif et innovant. Continue à explorer de nouvelles idées ! 🎨",
"Ton amitié est un cadeau précieux. Ta loyauté est inestimable ! 🔑",
"Tu es une personne pleine de bonté. Ta bienveillance est un trésor ! ❤️",
"Ta force intérieure est inspirante. Continue à croire en toi, tu es capable de tout ! 💪",
"Tu as une capacité incroyable à motiver les autres. Ton enthousiasme est contagieux ! 🎉",
"Ton sens de l'humour est unique. Continue à faire rire et sourire ceux qui t'entourent ! 😂",
"Tu es une personne pleine de joie de vivre. Ta positivité est un rayon de soleil ! ☀️",
"Ta présence est un véritable cadeau. Tu es une source de bonheur pour ceux qui t'entourent ! 😊",
"Tu as un cœur immense et généreux. Ta bienveillance est sans limites ! ❤️",
"Ton intelligence est remarquable. Continue à apprendre et à grandir ! 🧠",
"Tu es une personne pleine de sérénité. Ta tranquillité est apaisante ! 🌿",
"Ta capacité à écouter est exceptionnelle. Tu es une source de réconfort pour les autres ! 👂",
"Tu es une personne pleine de dynamisme. Ton énergie est communicative ! 🎉",
"Ton sourire est un véritable baume au cœur. Continue à répandre la joie autour de toi ! 😊",
"Tu as une âme pure et bienveillante. Ta gentillesse est un cadeau pour le monde ! 🌸",
"Ton enthousiasme est contagieux. Continue à inspirer ceux qui t'entourent ! 🎉",
"Tu es une personne pleine de charme naturel. Ton aura est magnétique ! 🌟",
"Ta loyauté est un trésor. Tu es un véritable pilier pour ceux qui t'entourent ! 🔑",
"Tu as une capacité incroyable à voir le bon côté des choses. Ton optimisme est une force ! 🌞",
"Ton calme est apaisant. Tu es une source de tranquillité pour les autres ! 🌿",
"Tu es une personne pleine de surprises. Continue à étonner et à enchanter ceux qui t'entourent ! 🌈",
"Ta persévérance est admirable. Continue à avancer, tu es capable de tout ! 💪",
"Tu as un esprit vif et intelligent. Ta curiosité est une source de découvertes ! 🌟",
"Ton amour pour les autres est palpable. Continue à répandre l'amour et la bienveillance ! ❤️",
"Tu es une personne pleine de grâce. Ton élégance est naturelle ! 🌸",
"Ta simplicité est touchante. Ton authenticité est rafraîchissante ! 🌿",
"Tu as un don pour faire sentir les gens spéciaux. Ton attention aux autres est précieuse ! 🌟",
"Ton énergie est revitalisante. Continue à être une source de vitalité pour ceux qui t'entourent ! 🌱",
"Tu es une personne pleine de courage. Ton audace est inspirante ! 💪",
"Ta générosité est sans limites. Continue à donner sans compter, tu fais une différence ! ❤️",
"Tu as une capacité incroyable à pardonner. Ta bienveillance est un exemple pour tous ! 🌸",
"Ton sens de l'organisation est impressionnant. Ta méthode est admirable ! 📚",
"Tu es une personne pleine de charisme. Ton aura est captivante ! 🌟",
"Ta douceur est réconfortante. Tu es une source de réconfort pour ceux qui t'entourent ! 🌿",
"Tu as un esprit créatif et innovant. Continue à explorer de nouvelles idées ! 🎨",
"Ton amitié est un cadeau précieux. Ta loyauté est inestimable ! 🔑",
"Tu es une personne pleine de bonté. Ta bienveillance est un trésor ! ❤️",
"Ta force intérieure est inspirante. Continue à croire en toi, tu es capable de tout ! 💪",
"Tu as une capacité incroyable à motiver les autres. Ton enthousiasme est contagieux ! 🎉",
"Ton sens de l'humour est unique. Continue à faire rire et sourire ceux qui t'entourent ! 😂",
"Tu es une personne pleine de joie de vivre. Ta positivité est un rayon de soleil ! ☀️",
"Ta présence est un véritable cadeau. Tu es une source de bonheur pour ceux qui t'entourent ! 😊",
"Tu as un cœur immense et généreux. Ta bienveillance est sans limites ! ❤️",
"Ton intelligence est remarquable. Continue à apprendre et à grandir ! 🧠",
"Tu es une personne pleine de sérénité. Ta tranquillité est apaisante ! 🌿",
"Ta capacité à écouter est exceptionnelle. Tu es une source de réconfort pour les autres ! 👂",
"Tu es une personne pleine de dynamisme. Ton énergie est communicative ! 🎉",
"Ton sourire est un véritable baume au cœur. Continue à répandre la joie autour de toi ! 😊",
"Tu as une âme pure et bienveillante. Ta gentillesse est un cadeau pour le monde ! 🌸",
"Ton enthousiasme est contagieux. Continue à inspirer ceux qui t'entourent ! 🎉",
"Tu es une personne pleine de charme naturel. Ton aura est magnétique ! 🌟",
"Ta loyauté est un trésor. Tu es un véritable pilier pour ceux qui t'entourent ! 🔑",
"Tu as une capacité incroyable à voir le bon côté des choses. Ton optimisme est une force ! 🌞",
]

# Test de l'initialisation
def test_initialization():
    if not TOKEN:
        print("Erreur: Token manquant !")
        return False
    print("Initialisation réussie !")
    return True

async def send_compliment(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Envoie un compliment en réponse à la commande /weewoo."""
    try:
        compliment = random.choice(COMPLIMENTS)
        message = f"🚨🚓🚨 __WEE WOO !!! POLICE DU SELF-LOVE !!__ 🚨🚓🚨\n{compliment}"
        await update.message.reply_text(message)
    except Exception as e:
        logging.error(f"Erreur lors de l'envoi du compliment : {e}")

def main():
    """Démarre le bot Telegram."""
    application = ApplicationBuilder().token(TOKEN).build()

    # Ajouter la gestion de la commande /weewoo
    application.add_handler(CommandHandler("weewoo", send_compliment))

    # Démarrer le polling
    application.run_polling()

if __name__ == "__main__":
    if test_initialization():
        logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
        logger = logging.getLogger(__name__)

        # Démarrer le bot dans le thread principal
        main()
